terms:
    - id: https://creativecommons.org/licenses/by/4.0/
      term: CC BY
    - id: http://creativecommons.org/publicdomain/zero/1.0/
      term: CC0 1.0 Universal
    - id: http://www.europeana.eu/portal/rights/rr-r.html
      term: All Rights Reserved
