terms:
    - id: Attribution (CC BY) https://creativecommons.org/licenses/by/4.0/
      term: Attribution (CC BY) https://creativecommons.org/licenses/by/4.0/
    - id: No Rights Reserved (CC0) https://creativecommons.org/publicdomain/zero/1.0/
      term: No Rights Reserved (CC0) https://creativecommons.org/publicdomain/zero/1.0/
    - id: None
      term: None
