development:
  adapter: solr
  url: <%= "#{ENV['SOLR_URL']}/hydra-development" || "http://127.0.0.1:#{ENV['SOLR_TEST_PORT'] || 8983}/solr/hydra-development" %>
test: &test
  adapter: solr
  url: <%= "#{ENV['SOLR_URL']}/hydra-development" || "http://127.0.0.1:#{ENV['SOLR_TEST_PORT'] || 8983}/solr/hydra-test" %>
production:
  adapter: solr
  url: <%= "#{ENV['SOLR_URL']}/hydra-development" || "http://your.production.server:8080/bl_solr/core0" %>