development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://localhost:8983/solr/development" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://localhost:8983/solr/test" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://localhost:8983/solr/blacklight-core" %>

