default: &default
  adapter: mysql2
  encoding: utf8
  pool: 10
  host: <%= ENV['DBHOST'] %>
  database: <%= ENV['DBNAME'] %>
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASSWD'] %>

development:
  <<: *default


production:
  <<: *default