development:
  exception_email_prefix: <%= ENV['EXCEPTION_EMAIL_PREFIX'] %>
  exception_recipients: <%= ENV['EXCEPTION_RECIPIENTS'] %>
  exception_sender_address: <%= ENV['EXCEPTION_SENDER_ADDRESS'] %>
test:
  exception_email_prefix: <%= ENV['EXCEPTION_EMAIL_PREFIX'] %>
  exception_recipients: <%= ENV['EXCEPTION_RECIPIENTS'] %>
  exception_sender_address: <%= ENV['EXCEPTION_SENDER_ADDRESS'] %>
production:
  exception_email_prefix: <%= ENV['EXCEPTION_EMAIL_PREFIX'] %>
  exception_recipients: <%= ENV['EXCEPTION_RECIPIENTS'] %>
  exception_sender_address: <%= ENV['EXCEPTION_SENDER_ADDRESS'] %>
