development:
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASSWD'] %>
  url: <%= ENV['FEDORA_URL'] %>
  base_path: /libra2/dev
  request: { timeout: 99999, open_timeout: 30}
test:
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASSWD'] %>
  url: <%= ENV['FEDORA_URL'] %>
  base_path: /libra2/test
  request: { timeout: 99999, open_timeout: 30}
production:
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASSWD'] %>
  url: <%= ENV['FEDORA_URL'] %>
  base_path: /libra2/prod
  request: { timeout: 99999, open_timeout: 30}
