default: &default
  url: <%= "redis://:#{ENV['REDIS_PASSWD'] || 'password'}@#{ENV['REDIS_HOST'] || 'localhost'}:#{ENV['REDIS_PORT'] || '6379'}" %>
  timeout: 5
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
