development:
  host: <%= ENV['REDIS_HOST'] || "localhost" %>
  port: <%= ENV['REDIS_PORT'] || "6379" %>
  timeout: 5
test:
  host: <%= ENV['REDIS_HOST'] || "localhost" %>
  port: <%= ENV['REDIS_PORT'] || "6379" %>
  timeout: 5
production:
  host: <%= ENV['REDIS_HOST'] || "localhost" %>
  port: <%= ENV['REDIS_PORT'] || "6379" %>
  timeout: 5