development:
  url: <%= "#{ENV['SOLR_URL']}/libra2" || "http://127.0.0.1:#{ENV['SOLR_TEST_PORT'] || 8983}/solr/hydra-development" %>
test:
  url: <%= "#{ENV['SOLR_URL']}/libra2" || "http://127.0.0.1:#{ENV['SOLR_TEST_PORT'] || 8983}/solr/hydra-test" %>
production:
  url: <%= "#{ENV['SOLR_URL']}/libra2" || "http://your.production.server:8080/bl_solr/core0" %>
